# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='game',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngame.proto\x12\x04game\"2\n\x10StartGameRequest\x12\x1e\n\nworld_size\x18\x01 \x01(\x0b\x32\n.game.Size\"B\n\x11StartGameResponse\x12\x0f\n\x07game_id\x18\x01 \x01(\x05\x12\x1c\n\tworld_map\x18\x02 \x01(\x0b\x32\t.game.Map\"\"\n\x0fPlayGameRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x10PlayGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x04Size\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"_\n\x03Map\x12\x1c\n\x08map_size\x18\x01 \x01(\x0b\x32\n.game.Size\x12\x1d\n\x05\x63\x65lls\x18\x02 \x03(\x0e\x32\x0e.game.Map.Cell\"\x1b\n\x04\x43\x65ll\x12\t\n\x05\x45mpty\x10\x00\x12\x08\n\x04Wall\x10\x01\x32\x7f\n\x04Game\x12<\n\tStartGame\x12\x16.game.StartGameRequest\x1a\x17.game.StartGameResponse\x12\x39\n\x08PlayGame\x12\x15.game.PlayGameRequest\x1a\x16.game.PlayGameResponseb\x06proto3'
)



_MAP_CELL = _descriptor.EnumDescriptor(
  name='Cell',
  full_name='game.Map.Cell',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Empty', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Wall', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=320,
  serialized_end=347,
)
_sym_db.RegisterEnumDescriptor(_MAP_CELL)


_STARTGAMEREQUEST = _descriptor.Descriptor(
  name='StartGameRequest',
  full_name='game.StartGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='world_size', full_name='game.StartGameRequest.world_size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=70,
)


_STARTGAMERESPONSE = _descriptor.Descriptor(
  name='StartGameResponse',
  full_name='game.StartGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game_id', full_name='game.StartGameResponse.game_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='world_map', full_name='game.StartGameResponse.world_map', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=138,
)


_PLAYGAMEREQUEST = _descriptor.Descriptor(
  name='PlayGameRequest',
  full_name='game.PlayGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='game.PlayGameRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=174,
)


_PLAYGAMERESPONSE = _descriptor.Descriptor(
  name='PlayGameResponse',
  full_name='game.PlayGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='game.PlayGameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=211,
)


_SIZE = _descriptor.Descriptor(
  name='Size',
  full_name='game.Size',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='game.Size.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='game.Size.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=250,
)


_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='game.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_size', full_name='game.Map.map_size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cells', full_name='game.Map.cells', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MAP_CELL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=347,
)

_STARTGAMEREQUEST.fields_by_name['world_size'].message_type = _SIZE
_STARTGAMERESPONSE.fields_by_name['world_map'].message_type = _MAP
_MAP.fields_by_name['map_size'].message_type = _SIZE
_MAP.fields_by_name['cells'].enum_type = _MAP_CELL
_MAP_CELL.containing_type = _MAP
DESCRIPTOR.message_types_by_name['StartGameRequest'] = _STARTGAMEREQUEST
DESCRIPTOR.message_types_by_name['StartGameResponse'] = _STARTGAMERESPONSE
DESCRIPTOR.message_types_by_name['PlayGameRequest'] = _PLAYGAMEREQUEST
DESCRIPTOR.message_types_by_name['PlayGameResponse'] = _PLAYGAMERESPONSE
DESCRIPTOR.message_types_by_name['Size'] = _SIZE
DESCRIPTOR.message_types_by_name['Map'] = _MAP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartGameRequest = _reflection.GeneratedProtocolMessageType('StartGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTGAMEREQUEST,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.StartGameRequest)
  })
_sym_db.RegisterMessage(StartGameRequest)

StartGameResponse = _reflection.GeneratedProtocolMessageType('StartGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTGAMERESPONSE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.StartGameResponse)
  })
_sym_db.RegisterMessage(StartGameResponse)

PlayGameRequest = _reflection.GeneratedProtocolMessageType('PlayGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLAYGAMEREQUEST,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.PlayGameRequest)
  })
_sym_db.RegisterMessage(PlayGameRequest)

PlayGameResponse = _reflection.GeneratedProtocolMessageType('PlayGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLAYGAMERESPONSE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.PlayGameResponse)
  })
_sym_db.RegisterMessage(PlayGameResponse)

Size = _reflection.GeneratedProtocolMessageType('Size', (_message.Message,), {
  'DESCRIPTOR' : _SIZE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.Size)
  })
_sym_db.RegisterMessage(Size)

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,), {
  'DESCRIPTOR' : _MAP,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:game.Map)
  })
_sym_db.RegisterMessage(Map)



_GAME = _descriptor.ServiceDescriptor(
  name='Game',
  full_name='game.Game',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=349,
  serialized_end=476,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartGame',
    full_name='game.Game.StartGame',
    index=0,
    containing_service=None,
    input_type=_STARTGAMEREQUEST,
    output_type=_STARTGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PlayGame',
    full_name='game.Game.PlayGame',
    index=1,
    containing_service=None,
    input_type=_PLAYGAMEREQUEST,
    output_type=_PLAYGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAME)

DESCRIPTOR.services_by_name['Game'] = _GAME

# @@protoc_insertion_point(module_scope)
